env:
     - CLOUDQA_API_KEY="Xs0yDZuD1jCGJPuJDCdNEfBfgy6cCLvztrW9lWomkPo=" CLOUDQA_SUITE_ID=5696 CLOUDQA_BROWSER=Chrome CLOUDQA_BUILD_TAG=122 CLOUDQA_VARIABLES="adminversion=3.3.11,buildversion=2021.165.3.725 fe9c935"

language: bash
before_script:
    - sudo apt-get update && sudo apt-get install -y jq
    
# first for production second for stage
    - curl -O https://cquserfiles.s3.amazonaws.com/5066/2f83516109de49578b0de948f3b74eaf/cloudqa-app-travisci.sh


script: 
    - bash cloudqa-app-travisci.sh 

