env:
     - CLOUDQA_API_KEY="xnEQ+zH5M+1kTXzHf2xLxRk7XW5/Yx2OZf31kmTJchU="
     - CLOUDQA_SUITE_ID=103
     - CLOUDQA_BROWSER=Chrome

language: bash

before_script:
    - sudo apt-get update && sudo apt-get install -y jq
    - curl -O https://cquserfiles.s3.amazonaws.com/6387/9f0402e7af0e4cc1b66a6aced0092ae9/cloudqa-app-travisci.sh
     
script: 
    - bash cloudqa-app-travisci.sh 

