env:
     - CLOUDQA_API_KEY="rKAN2ZIyUQDZLgL27E2oRmP5/uw4mZv4o7raYhQC+xE=" CLOUDQA_SUITE_ID=103
 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="adminversion=3.3.11,buildversion=2021.165.3.725 fe9c935"

language: bash
before_script:
    - sudo apt-get update && sudo apt-get install -y jq
    
    
 # first for stage second for production  
  - curl -O https://cquserfiles.s3.amazonaws.com/6387/4d7ae5e832154790839981eb2de6fc27/cloudqa-app-travisci.sh
  
# first for stage second for production 
# - curl -O https://cquserfiles.s3.amazonaws.com/5066/2f83516109de49578b0de948f3b74eaf/cloudqa-app-travisci.sh


script: 
    - bash cloudqa-app-travisci.sh 

